### ISSUE TITLE
The python autodoc in the sphinx documentation is broken

### ISSUE THREAD

**Issue by baldurmen** [isbg/isbg#112]
The lasts commits I made on the documentation broke the python functions autodoc and as a result these functions are not properly documented anymore.

We need to look at those commits and see what's the cause of it.

**Comment by baldurmen** [comment]
I have no problem building the docs in my dev environment, but both RTD and Travis fail at importing functions...

```

/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/master/docs/api_index.rst:13: WARNING: failed to import isbg.learn_mail
/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/master/docs/api_index.rst:13: WARNING: failed to import isbg.test_mail
/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/master/docs/api_index.rst:13: WARNING: failed to import isbg.unwrap
/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/master/docs/api_index.rst:13: WARNING: failed to import isbg.isbg.__version__
/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/master/docs/api_index.rst:13: WARNING: failed to import isbg.isbg.__exitcodes__
/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/master/docs/api_index.rst:13: WARNING: failed to import isbg.isbg.ISBG
/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/master/docs/api_index.rst:13: WARNING: failed to import isbg.isbg.ISBGError
WARNING: autodoc: failed to import module u'isbg'; the following exception was raised:
cannot import name imaputils
WARNING: autodoc: failed to import module u'isbg.__main__'; the following exception was raised:
cannot import name imaputils
WARNING: autodoc: failed to import module u'isbg.imaputils'; the following exception was raised:
cannot import name imaputils
WARNING: autodoc: failed to import module u'isbg.isbg'; the following exception was raised:
cannot import name imaputils
WARNING: autodoc: failed to import module u'isbg.sa_unwrap'; the following exception was raised:
cannot import name imaputils
WARNING: autodoc: failed to import module u'isbg.secrets'; the following exception was raised:
cannot import name imaputils
WARNING: autodoc: failed to import module u'isbg.spamproc'; the following exception was raised:
cannot import name imaputils
WARNING: autodoc: failed to import module u'isbg.utils'; the following exception was raised:
cannot import name imaputils
```

**Comment by baldurmen** [comment]
Ok, so Travis seems happy now, but RTD is still broken. The errors seems to spawn from an error in TypeVar():

```
WARNING: autodoc: failed to import module 'isbg'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/isbg/envs/latest/lib/python3.5/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/latest/isbg/__init__.py", line 16, in <module>
    from .isbg import ISBG, ISBGError, __version__, __exitcodes__, __license__
  File "/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/latest/isbg/isbg.py", line 26, in <module>
    from isbg import imaputils
  File "/home/docs/checkouts/readthedocs.org/user_builds/isbg/checkouts/latest/isbg/imaputils.py", line 45, in <module>
    Email = TypeVar(email.message.Message)
  File "/usr/lib/python3.5/typing.py", line 406, in __new__
    self = super().__new__(cls, name, (Final,), {}, _root=True)
  File "/usr/lib/python3.5/typing.py", line 107, in __new__
    return super().__new__(cls, name, bases, namespace)
TypeError: type() argument 1 must be str, not type
```

**Comment by baldurmen** [comment]
This has been fixed by RTD using a more recent version of Python3
