### ISSUE TITLE
Imaplib fails on Yahoo

### ISSUE THREAD

**Issue by windowswill** [isbg/isbg#120]
I got a Kali environment set up on my Windows 10 Pro sub shell and I went to run Spamassassin on my massive inbox (99,999+ emails) and I keep receiving the error in the title whenever I run the command.

The command I am using is as follows:
isbg --verbose --partialrun=500 --imaphost imap.mail.yahoo.com --imapuser username@yahoo.ca --learnspambox "[LearnSpam]"  --spaminbox "Bulk Mail"  --delete --learnthendestroy

The command seemed to work as intended for a while the first time before giving the error message and now when I repeat the command, the output is as follows:

```
Lock file is /home/will/.cache/isbg/lock
Trackfile starts with /home/will/.cache/isbg/track5ba75654eba5f37256b586efed6a4470
Password file is /home/will/.cache/isbg/.isbg-5ba75654eba5f37256b586efed6a4470
SpamFlags are []
Successfully read password file
('cabability',) = ('OK', ['IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT'])
Server capabilities: ['IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT']
('login', 'username@yahoo.ca', 'xxxxxxxx') = ('OK', ['LOGIN completed'])
Teach spam to SA from: [LearnSpam]
('select', '[LearnSpam]') = ('OK', ['35'])
('uid SEARCH', (None, 'ALL')) = ('OK', [''])
Writing pastuids for folder spam: 0 origpastuids, newpastuids: []
Traceback (most recent call last):
  File "/home/will/.local/bin/isbg", line 10, in <module>
    sys.exit(main())
  File "/home/will/.local/lib/python3.7/site-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/home/will/.local/lib/python3.7/site-packages/isbg/isbg.py", line 600, in do_isbg
    proc = self.do_spamassassin()
  File "/home/will/.local/lib/python3.7/site-packages/isbg/isbg.py", line 517, in do_spamassassin
    self.imap.select(self.imapsets.spaminbox, 1)
  File "/home/will/.local/lib/python3.7/site-packages/isbg/imaputils.py", line 180, in func_wrapper
    res = func(cls, *args, **kwargs)
  File "/home/will/.local/lib/python3.7/site-packages/isbg/imaputils.py", line 172, in func_wrapper
    return utils.get_ascii_or_value(func(cls, *args, **kwargs))
  File "/home/will/.local/lib/python3.7/site-packages/isbg/imaputils.py", line 260, in select
    return self.imap.select(mailbox, readonly)
  File "/usr/lib/python3.7/imaplib.py", line 745, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.7/imaplib.py", line 1027, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: EXAMINE command error: BAD [b'[CLIENTBUG] EXAMINE Additional arguments found after last expected argument']
```

I have replaced my actual email address with "username@yahoo.ca" for privacy reasons, but other than that, I have changed nothing.

**Comment by baldurmen** [comment]
Hi!

This a Yahoo-specific bug and is caused by bad CRLF formatting at end of IMAP command. Yahoo is stricter on the end of IMAP command lines (whereas other IMAP providers are more lenient on this).

I'll look what I can do about it, but I won't promise anything, as I neither have tons of time nor a Yahoo account.

Patches welcome!

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
