### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by berma83** [isbg/isbg#124]
Ubuntu 16.04

```
root@backup:~# isbg
Traceback (most recent call last):
  File "/usr/local/bin/isbg", line 6, in <module>
    from isbg.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/isbg/__init__.py", line 16, in <module>
    from .isbg import ISBG, ISBGError, __version__, __exitcodes__, __license__
  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 26, in <module>
    from isbg import imaputils
  File "/usr/local/lib/python3.5/dist-packages/isbg/imaputils.py", line 45, in <module>
    Email = TypeVar(email.message.Message)
  File "/usr/lib/python3.5/typing.py", line 406, in __new__
    self = super().__new__(cls, name, (Final,), {}, _root=True)
  File "/usr/lib/python3.5/typing.py", line 107, in __new__
    return super().__new__(cls, name, bases, namespace)
TypeError: type() argument 1 must be str, not type
root@backup:~#
```

**Comment by baldurmen** [comment]
Hi!

I distinctly remember hitting that error somewhere, but for the love of me I can't find where it was. If I recall correctly, it has something to do with the "typing" lib in Python 3.5 being quite new. A bunch of stuff has been fixed since then.

Could you please try with a more recent version of python?

**Comment by baldurmen** [comment]
Yes I knew it! I've seen that working with some old version of python3.5: https://github.com/isbg/isbg/issues/112#issuecomment-444584227

The python3.5 version in Ubuntu 16.04 is old and hasn't been patched since 2016. I'd suggest you migrate to a newer version of Ubuntu.
