### ISSUE TITLE
The savepw and noninteractive options are not working in branch 2.0

### ISSUE THREAD

**Issue by carlesmu** [isbg/isbg#81]
Using the noninteractive with a saved password using the version 1.0 I get this error:
```
Password file is /home/carlesmu/.isbg-6f417d524d9da20263eedd2815c1425a
Error reading pw!
Traceback (most recent call last):
  File "isbg/isbg.py", line 816, in do_isbg
    self.imappasswd = self.getpw(dehexof(open(self.passwdfilename, "rb").read().decode()), self.passwordhash)
  File "isbg/isbg.py", line 321, in getpw
    c = ord(data[i]) ^ hash[i]
TypeError: unsupported operand type(s) for ^: 'int' and 'str'
```

Also, when I try to save the password I get this error:
```
Traceback (most recent call last):
  File "isbg/isbg.py", line 906, in <module>
    isbg_run()
  File "isbg/isbg.py", line 903, in isbg_run
    isbg.do_isbg()
  File "isbg/isbg.py", line 838, in do_isbg
    f.write(hexof(self.setpw(self.imappasswd, self.passwordhash)).encode())
  File "isbg/isbg.py", line 333, in setpw
    res = [chr(x) for x in res]
TypeError: an integer is required
```

**Comment by baldurmen** [comment]
fixed by #86
