### ISSUE TITLE
Error on opening pipe to spamassassin executable

### ISSUE THREAD

**Issue by JohnKendrick** [isbg/isbg#88]
Hi,

I see the following error;

Traceback (most recent call last):
  File "/home/john/Software/isbg/isbg.py", line 552, in <module>
    p = Popen(satest, stdin=PIPE, stdout=PIPE, close_fds=True)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I am running on arch linux.  I am checking the mail of 4 email addresses.  I am running a cron job every 10 minutes.  The first of the email addresses often fails with the above error (although not always).
The other email addresses are always succesful.
I have tried using spamc as well as spamd with the same result.

The command line in the script look like this....

/usr/bin/python2 ~/Software/isbg/isbg.py --imaphost mail1.server.co.uk --imapuser mail1 --delete --expunge >> ~/Logs/spamlogs.log 2>&1
 
Any suggestions would be helpful

**Comment by JohnKendrick** [comment]
Update....
It looks like it is something to do with the environment that cron uses to run scripts.
I have migrated the cron script to a systemd timer and this seems to work without any problems.
