### ISSUE TITLE
Bug in error handling the lock file

### ISSUE THREAD

**Issue by JohnKendrick** [isbg/isbg#89]
Im now using branch 2.0
Saw this error....  
Traceback (most recent call last):
  File "isbg.py", line 906, in <module>
    isbg_run()
  File "isbg.py", line 903, in isbg_run
    isbg.do_isbg()
  File "isbg.py", line 803, in do_isbg
    errorexit(self.exitcodelocked)
TypeError: errorexit() takes exactly 2 arguments (1 given)

Looks like a simple ommision of a string in the call to errorexit()

**Comment by baldurmen** [comment]
This is fixed in #86 .
